server:
  port: 8080
  servlet:
    context-path: /

spring:
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
      order: 2
#    static-path-pattern: /**
#    #热部署--静态资源立即生效
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root